### ISSUE TITLE
New syntax.

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/AdeptImport#1]
@IsaacShelton After adding new syntax I think standart library should has this syntax too. I know that this is a lot of time.

**Comment by IsaacShelton** [comment]
@t0md3an I agree

This isn't high-priority for Adept 2.4 release, but for Adept 2.5 release this should be changed

**Comment by IsaacShelton** [comment]
I have since decided against it because:
- It's less friendly and breaks consistency with the original syntax
- There are better things to work on

For the most part, I intend on keeping the syntax similar between 2.x versions of Adept.
