### ISSUE TITLE
Add binding for IUP

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/AdeptImport#15]
https://sourceforge.net/projects/iup/

**Comment by IsaacShelton** [comment]
It looks like it might suffer from some of the same problems as dwindows, as it hasn't been updated in awhile. It also doesn't support macOS unfortunately.

It could be something to try though

**Comment by ghost** [comment]
> It looks like it might suffer from some of the same problems as dwindows, as it hasn't been updated in awhile. It also doesn't support macOS unfortunately.
> 
> It could be something to try though

It's still active developed and has an active community. It's only feature complete. Please see:

https://sourceforge.net/p/iup/mailman/iup-users/

**Comment by ghost** [comment]
@IsaacShelton I added it with https://github.com/AdeptLanguage/AdeptImport/pull/30. Please close this issue.
