### ISSUE TITLE
Translate `dwtest.c`

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/AdeptImport#31]
There is little to no documentation of the `dw` library. The only thing we have is an outdated API reference on their website. `dwtest.c` is the only source that demonstrate how `dw` works in practice.

**Comment by IsaacShelton** [comment]
Yes, `dw` is not a very good library. It should have probably have been a package instead of being in the standard library as it doesn't even work properly on macOS and requires the library to be installed on the system in order to use it.

Plus like what you said, the documentation sucks
