### ISSUE TITLE
OOP wrapper for IUP

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/AdeptImport#33]
IUP also has a C++ OOP wrapper. I attempted to make an OOP wrapper for Adept but very soon I realized it's not that easy. Adept lacks encapsulation support. Everything in Adept is `public`. There is no `private` or `protected`. A straight forward porting of the C++ OOP wrapper is not possible, so I suggest making a brand new Adept specific OOP wrapper for IUP.

**Comment by IsaacShelton** [comment]
Same as #32, it would be nice, but I don't use `iup` so I think it'd be better for someone who does to maintain it

Also yes, the encapsulation in Adept 2.x sucks.
