### ISSUE TITLE
Dump `expat` into a package, remove from AdeptImport

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/AdeptImport#38]
I translated it but have never tested if it worked or not. It shouldn't be qualified to be in AdeptImport. This is my bad. Sorry.

**Comment by ghost** [comment]
@IsaacShelton Please help me make the package. Thank you.

https://github.com/iahung2/adept.expat

**Comment by IsaacShelton** [comment]
It's good, I'll make an example PR against https://github.com/AdeptLanguage/AdeptLanguage.github.io

[Example PR](https://github.com/AdeptLanguage/AdeptLanguage.github.io/pull/2)
