### ISSUE TITLE
Adept binding for `libunistring`

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/AdeptImport#41]
https://packages.msys2.org/package/mingw-w64-x86_64-libunistring

**Comment by IsaacShelton** [comment]
A unicode library would be nice yes, probably best as package until the language has better support itself

**Comment by ghost** [comment]
> A unicode library would be nice yes, probably best as package until the language has better support itself

I think we will stuck with `libiconv`. `libunistring` and `icu` consisted of multiple headers. They are too large to translate manually.
