### ISSUE TITLE
Adept binding for `libgc`

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/AdeptImport#44]
### Discussed in https://github.com/AdeptLanguage/Adept/discussions/230

<div type='discussions-op-text'>

<sup>Originally posted by **ghost** November 22, 2023</sup>
Github: https://github.com/ivmai/bdwgc

MSYS2: https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-gc</div>

**Comment by ghost** [comment]
What do you think about `libgc`? I think `libgc` could be used for optional GC (https://github.com/AdeptLanguage/Adept/issues/279).

**Comment by ghost** [comment]
Update: I will use Adept like a better version of C, and use only manual memory management. This is guaranteed to work regardless of what new memory management model you will introduce in Adept 3.0

**Comment by IsaacShelton** [comment]
Same as https://github.com/AdeptLanguage/Adept/issues/312#issuecomment-1953282775

**Comment by IsaacShelton** [comment]
GC would be a good option though yes
