### ISSUE TITLE
Please add gzip binding

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/AdeptImport#9]
This is a very useful library that I think we should be able to use.

**Comment by IsaacShelton** [comment]
(same response as #7)

I agree

I think a translation layer or C header support would allow this the best

Like other bindings requests, I will take a look into them when I become less busy

**Comment by ghost** [comment]
@IsaacShelton `gzip` is an utility and not a library. Perhaps what the OP actually asked for is `zlib` (and he has already asked for it on #7). Please close this issue. Thank you.
